services:
  myits:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3001:3000'
    networks:
      - praktika_network

networks:
  praktika_network:
    driver: bridge
